import Vue from 'vue'
import Vuex from 'vuex'

//挂载Vuex
Vue.use(Vuex)

//创建VueX对象
const store = new Vuex.Store({
    state: {
        //存放的键值对就是所要管理的状态
        testName: "201810",
        testRegion: "NA",

        statusReading: "process",
        statusWL: "wait",
        statusMathNC: "wait",
        statusMath: "wait",
        statusEssay: "wait",

        showReading: false,
        showWL: false,
        showMathNC: false,
        showMath: false,

        countReading: 0,
        countWL: 0,
        countMathNC: 0,
        countMath: 0,

        wrongReading: [],
        wrongWL: [],
        wrongMathNC: [],
        wrongMath: [],

        step: 0,

        name: "",

        section_1: [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            32,
            33,
            34,
            35,
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44,
            45,
            46,
            47,
            48,
            49,
            50,
            51,
            52
        ],
        section_1_answer: [
            "B",
            "A",
            "C",
            "D",
            "C",

            "C",
            "B",
            "B",
            "A",
            "B",

            "C",
            "D",
            "A",
            "C",
            "D",

            "C",
            "C",
            "B",
            "B",
            "A",

            "A",
            "C",
            "D",
            "B",
            "A",

            "A",
            "C",
            "D",
            "C",
            "C",

            "B",
            "B",
            "A",
            "A",
            "C",

            "D",
            "B",
            "A",
            "A",
            "C",

            "D",
            "C",
            "C",
            "B",
            "B",

            "A",
            "A",
            "C",
            "D",
            "B",

            "A",
            "A"
        ],
        section_1_user_answer: [],
        section_2: [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            32,
            33,
            34,
            35,
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        section_2_answer: [
            "B",
            "A",
            "C",
            "D",
            "C",
            "C",
            "B",
            "B",
            "A",
            "B",
            "C",
            "D",
            "A",
            "C",
            "D",
            "C",
            "C",
            "B",
            "B",
            "A",
            "A",
            "C",
            "D",
            "B",
            "A",
            "A",
            "C",
            "D",
            "C",
            "C",
            "B",
            "B",
            "A",
            "A",
            "C",
            "D",
            "B",
            "A",
            "A",
            "C",
            "D",
            "C",
            "C",
            "B"
        ],
        section_2_user_answer: [],
        section_3: [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20
        ],
        section_3_answer: [
            "B",
            "A",
            "C",
            "D",
            "C",

            "C",
            "B",
            "B",
            "A",
            "B",

            "C",
            "D",
            "A",
            "C",
            "D",

            "2",
            "4/5",
            "0.6",
            "0.7",
            "154"
        ],
        section_3_user_answer: [],
        section_4: [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            32,
            33,
            34,
            35,
            36,
            37,
            38
        ],
        section_4_answer: [
            "B",
            "A",
            "C",
            "D",
            "C",

            "C",
            "B",
            "B",
            "A",
            "B",

            "C",
            "D",
            "A",
            "C",
            "D",

            "C",
            "C",
            "B",
            "B",
            "A",

            "A",
            "C",
            "D",
            "B",
            "A",

            "A",
            "C",
            "D",
            "C",
            "C",

            "2",
            "4/5",
            "0.6",
            "0.7",
            "154",

            "3",
            "0",
            "1405"
        ],
        section_4_user_answer: [],
    },
    mutations: {
        stepReading(state) {
            state.step = 0
        },
        stepWL(state) {
            state.step = 1
        },
        stepMathNC(state) {
            state.step = 2
        },
        stepMath(state) {
            state.step = 3
        },
        stepEssay(state) {
            state.step = 4
        }
    }
})

export default store